services:
  db:
    build: . 
    env_file:
    - .env
    container_name: mydb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data