services:
  db:
    image: postgres:16
    env_file:
    - .env
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT_FROM_CONTAINER}:${DB_PORT_IN_CONTAINER}"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 7
  etl:
    build: .
    container_name: etl
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${API_PORT_FROM_CONTAINER}:${API_PORT_IN_CONTAINER}"